defaults: &defaults
  tracker_id: SinatraTracker
  announce_interval: 1800
  timeout_interval: 2000
  min_announce_interval: 900
  allow_unregistered_torrents: true
  allow_noncompact: true
  full_scrape: false
  
development:
  <<: *defaults
  mongo_uri: mongodb://test:test@127.0.0.1:27017/tracker

production:
  <<: *defaults
  mongo_uri: <%= ENV['MONGOLAB_URL'] %>
  
test:
  <<: *defaults
  mongo_uri: mongodb://test:test@127.0.0.1:27017/tracker_test